package dtcimport

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// WriteCredits records where the catalog came from.
//
// It is generated from the same source list that produced the data, so the
// attribution cannot drift from what was actually imported — which is the
// failure mode a hand-maintained credits file always eventually hits.
func WriteCredits(path string, result *Result) error {
	var b strings.Builder

	b.WriteString(`# Credits

The trouble-code catalog in ` + "`internal/dtc/data/`" + ` is not original work. It is
assembled by ` + "`cargo import`" + ` from the open datasets below, and this file is
regenerated by the same command.

`)

	fmt.Fprintf(&b, "Current catalog: **%d generic** codes and **%d manufacturer** definitions across **%d makes**.\n\n",
		result.Generic, result.Manufacturer, result.Makes)

	b.WriteString("## Datasets\n\n| Project | Licence | Copyright |\n|---|---|---|\n")
	for _, l := range result.Licences {
		fmt.Fprintf(&b, "| [%s](%s) | %s | %s |\n",
			strings.TrimPrefix(l.URL, "https://github.com/"), l.URL, l.SPDX, l.Holder)
	}

	b.WriteString(`
Both are MIT licensed, and their terms are compatible with this project's.

## What that licence does and does not cover

An MIT grant from a dataset's maintainer covers their compilation. It does not
settle the rights to the underlying definitions, which these projects gathered
from sources they do not identify.

The authoritative definitions live in **SAE J2012**, which is a paid standard,
and its machine-readable Digital Annex is a separate paid product. Every freely
available list is downstream of it. Manufacturer codes are more restricted
still: J2012 reserves the ranges but the meanings belong to each marque's
service documentation.

Treat the catalog as a helpful index, not an authority. That is why every
description carries its source through to the display, why manufacturer codes
are tagged with the make that defined them, and why an unmatched code falls
back to what the encoding itself proves rather than to a guess.

## Libraries

`)

	libs := []struct{ name, url, licence string }{
		{"rivo/tview", "https://github.com/rivo/tview", "MIT"},
		{"gdamore/tcell", "https://github.com/gdamore/tcell", "Apache-2.0"},
		{"spf13/cobra", "https://github.com/spf13/cobra", "Apache-2.0"},
		{"spf13/viper", "https://github.com/spf13/viper", "MIT"},
		{"uber-go/zap", "https://github.com/uber-go/zap", "MIT"},
		{"tarm/serial", "https://github.com/tarm/serial", "BSD-3-Clause"},
	}
	sort.Slice(libs, func(i, j int) bool { return libs[i].name < libs[j].name })

	b.WriteString("| Library | Licence |\n|---|---|\n")
	for _, l := range libs {
		fmt.Fprintf(&b, "| [%s](%s) | %s |\n", l.name, l.url, l.licence)
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}
